apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: touni-minuit
  name: touni-minuit
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: touni-minuit
status:
  loadBalancer: {}
